### PR TITLE
Wait for route data, as well as checking if there are no dogs.

### PR DESCRIPTION
**Pull request by MatthewLilley**

### CODE REVIEW

**Comment by MatthewLilley** [comment]
Added fixes for errors, and v-active on tabs.

**Comment by OzanKurt** [comment]
@MatthewLilley :+1:

**Comment by kcalliauw** [comment]
Please fix the merge conflicts for this first, and I will accept the PR.

**Comment by OzanKurt** [comment]
@kcalliauw :+1: 

Thanks for this repository by the way. It helped me a lot to understand how these stuff work.

**Pull request closed without merging**
